-- `generated always as identity` refuses any explicit value for the column, and an upsert is
-- an INSERT ... ON CONFLICT that must name `id` to find the conflict — so every save of an
-- existing template failed with 428C9 before it reached the audit write.
-- `by default` still generates the id when the insert omits it, which is what the add path does.
alter table public.kpi_template alter column id set generated by default;;
