-- ============================================================
-- เช็คลิสต์ทรัพย์เด่น (A-List / Exclusive) — หน้าตั้งค่าสุดท้ายที่ยังไม่มีตารางเก็บ
-- ============================================================
-- 2 ชั้น: "เทมเพลต" (CEO/Listing Support แก้ในหน้าตั้งค่า) กับ "ความคืบหน้าต่อทรัพย์"
-- (ทีมติ๊กในหน้าทรัพย์) — ของเดิมอยู่ใน ChecklistProvider ทั้งคู่ **ติ๊กแล้วรีเฟรชหาย**
--
-- ⚠️ Ben ตัดสินใจ 2026-08-23: ทำตารางใหม่ แล้ว **เลิกใช้ 5 คอลัมน์ที่ Support กรอกเอง**
--    ใน main_10_potential_listing (template_link · marketplace · profile · group_date ·
--    group_boost_date) ซึ่งซ้ำกับเทมเพลต "ลงประกาศ A List" เป๊ะทั้ง 7 ข้อ
--    → ข้อมูลไม่หาย เพราะทั้ง 5 คอลัมน์ยังว่าง 0/210 อยู่แล้ว
--    → main_10 ยังทำหน้าที่เดิมคือ "ทรัพย์ไหนเป็น A List" (trigger auto sync) ไม่ได้ถูกแตะ
--    (คอลัมน์ ddproperty/livinginsider/propertyhub_link ใน main_10 ยัง auto sync จาก main_4
--     ตามเดิม — ไม่ใช่ของที่ Support กรอก)

create table if not exists public.checklist_template (
  id         bigint generated by default as identity primary key,
  name       text not null,
  -- ระดับที่ใช้เทมเพลตนี้ — ทรัพย์ Normal ไม่มีเช็คลิสต์เลยโดยตั้งใจ
  applies_to text[] not null default '{}'
             check (applies_to <@ array['a_list','exclusive']::text[] and array_length(applies_to,1) >= 1),
  sort       int not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.checklist_template_item (
  id          bigint generated by default as identity primary key,
  template_id bigint not null references public.checklist_template(id) on delete cascade,
  label       text not null,
  -- task=ติ๊ก · document=แนบลิงก์เอกสาร · date=กำหนดวัน · link=วางลิงก์ · cadence=โพสต์ซ้ำทุก N วัน
  item_type   text not null default 'task'
              check (item_type in ('task','document','date','link','cadence')),
  -- บทบาทที่รับผิดชอบขั้นตอนนี้ · on delete set null: ลบบทบาททิ้งแล้วเช็คลิสต์ต้องไม่หายไปด้วย
  role        text references public.roles(id) on update cascade on delete set null,
  repeat_days int,
  sort        int not null default 0,
  -- cadence เท่านั้นที่มีรอบโพสต์ซ้ำ ชนิดอื่นถือค่าไว้จะกลายเป็นตัวเลขที่ไม่มีใครใช้แต่ยังโชว์
  constraint checklist_item_repeat_coherent check (
    (item_type = 'cadence' and repeat_days is not null and repeat_days > 0) or
    (item_type <> 'cadence' and repeat_days is null)
  )
);
create index if not exists ix_checklist_item_template on public.checklist_template_item(template_id);

-- ความคืบหน้าต่อทรัพย์ — แถวเกิดเมื่อมีคนแตะข้อนั้นครั้งแรกเท่านั้น (live join กับเทมเพลต
-- ไม่ใช่ snapshot) → เพิ่มข้อใหม่ในเทมเพลต ทรัพย์ทุกหลังเห็นทันทีโดยไม่ต้อง backfill
create table if not exists public.listing_checklist_item (
  listing_id       text   not null references public.main_4_listing_database(listing_id) on update cascade on delete cascade,
  template_item_id bigint not null references public.checklist_template_item(id) on delete cascade,
  completed_at     timestamptz,
  completed_by     text references public.main_1_hr(employee_code) on update cascade,
  -- date = กำหนดส่ง · cadence = วันที่โพสต์ล่าสุด
  due_date         date,
  -- link/document ใช้ช่องเดียวกัน — Ben เลือกเก็บ "ลิงก์ Google Drive" ไม่อัปไฟล์เข้าระบบ
  -- (ไม่เอาสำเนาบัตร ปชช./โฉนดเข้า Supabase + ไม่กินโควตาที่รูปทรัพย์ใช้อยู่)
  url              text,
  note             text,
  updated_at       timestamptz default now(),
  primary key (listing_id, template_item_id)
);

-- ── RLS ──────────────────────────────────────────────────────
-- เทมเพลต: อ่านได้ทุกคนที่ล็อกอิน (หน้าทรัพย์ต้องเรนเดอร์) · แก้ได้ด้วย checklists.manage
-- ความคืบหน้า: ติ๊กได้เท่ากับสิทธิ์แก้ทรัพย์ — งานเช็คลิสต์เป็นงานข้ามทีม (เซล/Support/
-- การตลาด ทำคนละข้อในทรัพย์หลังเดียวกัน) ถ้าผูกกับเจ้าของทรัพย์คนเดียวจะไม่มีใครติ๊กได้เลย
alter table public.checklist_template        enable row level security;
alter table public.checklist_template_item   enable row level security;
alter table public.listing_checklist_item    enable row level security;
revoke all on public.checklist_template      from anon;
revoke all on public.checklist_template_item from anon;
revoke all on public.listing_checklist_item  from anon;
grant select, insert, update, delete on public.checklist_template        to authenticated;
grant select, insert, update, delete on public.checklist_template_item   to authenticated;
grant select, insert, update, delete on public.listing_checklist_item    to authenticated;

do $do$
declare t text;
begin
  foreach t in array array['checklist_template','checklist_template_item'] loop
    execute format('drop policy if exists p_select on public.%I', t);
    execute format('drop policy if exists p_insert on public.%I', t);
    execute format('drop policy if exists p_update on public.%I', t);
    execute format('drop policy if exists p_delete on public.%I', t);
    execute format('create policy p_select on public.%I for select to authenticated using (true)', t);
    execute format($f$create policy p_insert on public.%I for insert to authenticated
      with check ((select has_perm('checklists.manage')) or (select has_perm('roles.manage')))$f$, t);
    execute format($f$create policy p_update on public.%I for update to authenticated
      using      ((select has_perm('checklists.manage')) or (select has_perm('roles.manage')))
      with check ((select has_perm('checklists.manage')) or (select has_perm('roles.manage')))$f$, t);
    execute format($f$create policy p_delete on public.%I for delete to authenticated
      using ((select has_perm('checklists.manage')) or (select has_perm('roles.manage')))$f$, t);
  end loop;
end
$do$;

drop policy if exists p_select on public.listing_checklist_item;
drop policy if exists p_insert on public.listing_checklist_item;
drop policy if exists p_update on public.listing_checklist_item;
drop policy if exists p_delete on public.listing_checklist_item;
create policy p_select on public.listing_checklist_item for select to authenticated
  using ((select has_perm('listings.view')) or (select has_perm('roles.manage')));
create policy p_insert on public.listing_checklist_item for insert to authenticated
  with check ((select has_perm('listings.edit')) or (select has_perm('listings.marketing'))
              or (select has_perm('checklists.manage')) or (select has_perm('roles.manage')));
create policy p_update on public.listing_checklist_item for update to authenticated
  using      ((select has_perm('listings.edit')) or (select has_perm('listings.marketing'))
              or (select has_perm('checklists.manage')) or (select has_perm('roles.manage')))
  with check ((select has_perm('listings.edit')) or (select has_perm('listings.marketing'))
              or (select has_perm('checklists.manage')) or (select has_perm('roles.manage')));
create policy p_delete on public.listing_checklist_item for delete to authenticated
  using ((select has_perm('listings.edit')) or (select has_perm('listings.marketing'))
         or (select has_perm('checklists.manage')) or (select has_perm('roles.manage')));;
