-- A revenue target that belongs to a TEAM, not a person.
--
-- Same shape as the per-agent rows in `targets` (period length + optional period_key
-- override, standing row = ''), so the dashboard resolves both with one rule and nothing
-- is ever pro-rated. Its own table because `targets` is employee-keyed end to end
-- (NOT NULL employee_code, RLS on it, unique indexes on it) and a sentinel code would
-- have been a lie the policies could not reason about.
--
-- `teams.revenue_goal` (one bare number, never written by the app) is superseded by
-- this table and left in place; drop it in a later migration once nothing reads it.
create table public.team_revenue_targets (
  id          bigint generated by default as identity primary key,
  team_id     text not null references public.teams(id) on delete cascade,
  period      text not null check (period in ('day','week','month','quarter','year')),
  -- '' = standing figure for every period of that length; 'YYYY-MM' / 'YYYY-Qn' / … = one-off override.
  period_key  text not null default '',
  target      numeric not null check (target > 0),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (team_id, period, period_key)
);
comment on table public.team_revenue_targets is
  'Team-level revenue targets (full commission received by the company). One row per team × period length, plus optional per-period overrides. Supersedes teams.revenue_goal.';

alter table public.team_revenue_targets enable row level security;
revoke all on public.team_revenue_targets from anon;

-- Readable by anyone signed in, like `teams` itself: a team target is a shared number,
-- not private performance data.
create policy p_select on public.team_revenue_targets
  for select using (true);
-- Written by whoever may set official targets — the same gate as a salesperson's number.
create policy p_insert on public.team_revenue_targets
  for insert with check (has_perm('targets.set') or has_perm('roles.manage'));
create policy p_update on public.team_revenue_targets
  for update using (has_perm('targets.set') or has_perm('roles.manage'));
create policy p_delete on public.team_revenue_targets
  for delete using (has_perm('targets.set') or has_perm('roles.manage'));

-- Signed commission per agent per month, for a set of agents at once. The team tab's one
-- read for the tiles, the per-person table and the trend. Same rules as
-- dash_revenue_monthly: `close` counts pending+success by closing_date on forecast_share,
-- `win` counts success by transfer_date on real_share. Invoker rights, so RLS on
-- closed_case_agent decides which agents' rows the caller may see.
create or replace function public.dash_revenue_by_agent(
  p_codes text[], p_from date, p_to date, p_basis text default 'close'
)
returns table(employee_code text, month text, total numeric, cases bigint)
language sql stable
set search_path = public
as $$
  select
    a.employee_code,
    to_char(case when p_basis = 'win' then c.transfer_date else c.closing_date end, 'YYYY-MM') as month,
    coalesce(sum(case when p_basis = 'win' then a.real_share else a.forecast_share end), 0)::numeric as total,
    count(*)::bigint as cases
  from closed_case_agent a
  join closed_case c on c.case_id = a.case_id
  where a.employee_code = any (p_codes)
    and (case when p_basis = 'win' then c.transfer_date else c.closing_date end) between p_from and p_to
    and (case when p_basis = 'win' then c.status = 'success' else c.status in ('pending', 'success') end)
  group by 1, 2
  order by 1, 2
$$;
revoke all on function public.dash_revenue_by_agent(text[], date, date, text) from public, anon;
grant execute on function public.dash_revenue_by_agent(text[], date, date, text) to authenticated;;
